"""Parallel Works SDK - Official Python client for the ACTIVATE platform API."""

from parallelworks_client.auth import (
    API_KEY_PREFIX,
    OPAQUE_ACCESS_TOKEN_PREFIX,
    CLIAuth,
    Client,
    CredentialConfig,
    CredentialError,
    Identity,
    NoPlatformHostError,
    SignInExpiredError,
    SyncClient,
    default_credential_config_path,
    extract_platform_host,
    is_api_key,
    is_token,
    load_credential_config,
    resolve_command,
    resolve_identity,
)
from parallelworks_client.problem import (
    FieldError,
    ProblemError,
    accept_language_from_env,
    raise_for_problem,
)

__all__ = [
    "API_KEY_PREFIX",
    "OPAQUE_ACCESS_TOKEN_PREFIX",
    "CLIAuth",
    "Client",
    "CredentialConfig",
    "CredentialError",
    "FieldError",
    "Identity",
    "NoPlatformHostError",
    "ProblemError",
    "SignInExpiredError",
    "SyncClient",
    "accept_language_from_env",
    "default_credential_config_path",
    "extract_platform_host",
    "is_api_key",
    "is_token",
    "load_credential_config",
    "raise_for_problem",
    "resolve_command",
    "resolve_identity",
]
