// Code generated by openapi-client-generator. DO NOT EDIT.
package parallelworks

import (
	"encoding/base64"
	"net/http"
)

// AuthProvider authenticates HTTP requests.
type AuthProvider interface {
	Apply(req *http.Request) error
}

// BearerAuth authenticates via Bearer token.
type BearerAuth struct {
	Token string
}

func (a *BearerAuth) Apply(req *http.Request) error {
	req.Header.Set("Authorization", "Bearer "+a.Token)
	return nil
}

// APIKeyAuth authenticates via API key.
type APIKeyAuth struct {
	Key      string
	Header   string // header name, e.g. "X-API-Key"
	Location string // "header", "query", "cookie"
}

func (a *APIKeyAuth) Apply(req *http.Request) error {
	switch a.Location {
	case "query":
		q := req.URL.Query()
		q.Set(a.Header, a.Key)
		req.URL.RawQuery = q.Encode()
	case "cookie":
		req.AddCookie(&http.Cookie{Name: a.Header, Value: a.Key})
	default: // header
		req.Header.Set(a.Header, a.Key)
	}
	return nil
}

// BasicAuth authenticates via HTTP Basic authentication.
type BasicAuth struct {
	Username string
	Password string
}

func (a *BasicAuth) Apply(req *http.Request) error {
	credentials := base64.StdEncoding.EncodeToString([]byte(a.Username + ":" + a.Password))
	req.Header.Set("Authorization", "Basic "+credentials)
	return nil
}

// WithAuth sets the authentication provider.
func WithAuth(auth AuthProvider) ClientOption {
	return func(c *Client) {
		c.auth = auth
	}
}
