// Code generated by openapi-client-generator. DO NOT EDIT.

package parallelworks

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

// Client is an API client for Parallel Works API.
type Client struct {
	baseURL     string
	httpClient  *http.Client
	userAgent   string
	auth        AuthProvider
	retryConfig *RetryConfig
	middlewares []Middleware
}

// NewClient creates a new API client with the given base URL and options.
func NewClient(baseURL string, opts ...ClientOption) *Client {
	c := &Client{
		baseURL:    strings.TrimRight(baseURL, "/"),
		httpClient: http.DefaultClient,
		userAgent:  "parallelworks-go-sdk/7",
	}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

// do executes an HTTP request and decodes the response. contentType selects the
// request body encoding and is sent as the Content-Type header. An operation
// whose spec declares an empty security requirement passes authenticated false,
// since it says it takes no credential.
func (c *Client) do(ctx context.Context, method string, path string, body any, contentType string, result any, accept string, authenticated bool, headers ...http.Header) error {
	resp, err := c.send(ctx, method, path, body, contentType, accept, authenticated, headers...)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("reading response body: %w", err)
	}

	if result != nil && len(respBody) > 0 {
		ct := resp.Header.Get("Content-Type")
		switch {
		case strings.Contains(ct, "json") || ct == "":
			if err := json.Unmarshal(respBody, result); err != nil {
				return fmt.Errorf("decoding response body: %w", err)
			}
		case isRawResult(result, respBody):
			// A body the operation types as bytes or text is itself the value,
			// so it is taken verbatim rather than parsed.
		default:
			// A server that labels JSON as something else is common enough to
			// try anyway, and the media types name each other when it fails.
			if err := json.Unmarshal(respBody, result); err != nil {
				return fmt.Errorf("decoding response body: asked for %s and the server sent %s: %w", accept, ct, err)
			}
		}
	}

	return nil
}

// doStream executes an HTTP request and hands back the response with its body
// unread, for an operation whose payload arrives an event at a time. The caller
// closes it.
func (c *Client) doStream(ctx context.Context, method string, path string, body any, contentType string, accept string, authenticated bool, headers ...http.Header) (*http.Response, error) {
	return c.send(ctx, method, path, body, contentType, accept, authenticated, headers...)
}

// send runs the request, retrying as the config allows, and returns the response
// with its body still unread. A status outside 2xx comes back as an *APIError
// carrying the body, so a body is left open only for a response that succeeded.
func (c *Client) send(ctx context.Context, method string, path string, body any, contentType string, accept string, authenticated bool, headers ...http.Header) (*http.Response, error) {
	fullURL := c.baseURL + path

	var payload []byte
	if hasRequestBody(body) {
		var err error
		payload, contentType, err = encodeRequestBody(body, contentType)
		if err != nil {
			return nil, err
		}
	}

	// Build the transport function.
	transport := func(req *http.Request) (*http.Response, error) {
		return c.httpClient.Do(req)
	}

	// Wrap with middleware chain (applied in reverse order so first middleware runs first).
	for i := len(c.middlewares) - 1; i >= 0; i-- {
		mw := c.middlewares[i]
		next := transport
		transport = func(req *http.Request) (*http.Response, error) {
			return mw(req, next)
		}
	}

	maxAttempts := 1
	if c.retryConfig != nil {
		maxAttempts = 1 + c.retryConfig.MaxRetries
	}

	for attempt := 0; attempt < maxAttempts; attempt++ {
		// Check context cancellation before each attempt.
		if err := ctx.Err(); err != nil {
			return nil, err
		}

		var bodyReader io.Reader
		if payload != nil {
			bodyReader = bytes.NewReader(payload)
		}

		req, err := http.NewRequestWithContext(ctx, method, fullURL, bodyReader)
		if err != nil {
			return nil, fmt.Errorf("creating request: %w", err)
		}

		if payload != nil {
			req.Header.Set("Content-Type", contentType)
			// Set GetBody so request body can be re-read on retries.
			bodyBytes := payload
			req.GetBody = func() (io.ReadCloser, error) {
				return io.NopCloser(bytes.NewReader(bodyBytes)), nil
			}
		}
		req.Header.Set("Accept", accept)
		if c.userAgent != "" {
			req.Header.Set("User-Agent", c.userAgent)
		}
		for _, h := range headers {
			for k, vs := range h {
				for _, v := range vs {
					req.Header.Set(k, v)
				}
			}
		}

		if c.auth != nil && authenticated {
			if err := c.auth.Apply(req); err != nil {
				return nil, fmt.Errorf("applying auth: %w", err)
			}
		}

		resp, err := transport(req)
		if err != nil {
			// A middleware may return a response alongside the error; don't leak its body.
			if resp != nil {
				resp.Body.Close()
			}
			// Retry idempotent requests on transient network errors.
			if c.retryConfig != nil && attempt < maxAttempts-1 && isIdempotentMethod(method) && isRetryableNetworkError(err) {
				timer := time.NewTimer(retryDelay(attempt, *c.retryConfig, nil))
				select {
				case <-ctx.Done():
					timer.Stop()
					return nil, ctx.Err()
				case <-timer.C:
				}
				continue
			}
			return nil, fmt.Errorf("executing request: %w", err)
		}

		// Check if we should retry.
		if c.retryConfig != nil && attempt < maxAttempts-1 && shouldRetryStatus(method, resp.StatusCode, *c.retryConfig) && withinRetryBudget(resp, *c.retryConfig) {
			delay := retryDelay(attempt, *c.retryConfig, resp)
			// The next attempt replaces this response, so its body is drained
			// rather than read: draining lets the connection be reused.
			io.Copy(io.Discard, resp.Body)
			resp.Body.Close()
			timer := time.NewTimer(delay)
			select {
			case <-ctx.Done():
				timer.Stop()
				return nil, ctx.Err()
			case <-timer.C:
			}
			continue
		}

		captureResponse(ctx, resp)

		if resp.StatusCode < 200 || resp.StatusCode >= 300 {
			respBody, readErr := io.ReadAll(resp.Body)
			resp.Body.Close()
			if readErr != nil {
				return nil, fmt.Errorf("reading response body: %w", readErr)
			}
			return nil, &APIError{StatusCode: resp.StatusCode, Status: resp.Status, Body: respBody}
		}

		return resp, nil
	}

	return nil, fmt.Errorf("max retries exceeded")
}
