// Code generated by openapi-client-generator. DO NOT EDIT.
package parallelworks

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

// Client is an API client for Parallel Works API.
type Client struct {
	baseURL     string
	httpClient  *http.Client
	userAgent   string
	auth        AuthProvider
	retryConfig *RetryConfig
	middlewares []Middleware
}

// NewClient creates a new API client with the given base URL and options.
func NewClient(baseURL string, opts ...ClientOption) *Client {
	c := &Client{
		baseURL:    strings.TrimRight(baseURL, "/"),
		httpClient: http.DefaultClient,
		userAgent:  "openapi-client-generator/1.0",
	}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

// do executes an HTTP request and decodes the response.
func (c *Client) do(ctx context.Context, method string, path string, body any, result any, accept string, headers ...http.Header) error {
	fullURL := c.baseURL + path

	var jsonBody []byte
	if body != nil {
		var err error
		jsonBody, err = json.Marshal(body)
		if err != nil {
			return fmt.Errorf("encoding request body: %w", err)
		}
	}

	// Build the transport function.
	transport := func(req *http.Request) (*http.Response, error) {
		return c.httpClient.Do(req)
	}

	// Wrap with middleware chain (applied in reverse order so first middleware runs first).
	for i := len(c.middlewares) - 1; i >= 0; i-- {
		mw := c.middlewares[i]
		next := transport
		transport = func(req *http.Request) (*http.Response, error) {
			return mw(req, next)
		}
	}

	maxAttempts := 1
	if c.retryConfig != nil {
		maxAttempts = 1 + c.retryConfig.MaxRetries
	}

	for attempt := 0; attempt < maxAttempts; attempt++ {
		// Check context cancellation before each attempt.
		if err := ctx.Err(); err != nil {
			return err
		}

		var bodyReader io.Reader
		if jsonBody != nil {
			bodyReader = bytes.NewReader(jsonBody)
		}

		req, err := http.NewRequestWithContext(ctx, method, fullURL, bodyReader)
		if err != nil {
			return fmt.Errorf("creating request: %w", err)
		}

		if jsonBody != nil {
			req.Header.Set("Content-Type", "application/json")
			// Set GetBody so request body can be re-read on retries.
			bodyBytes := jsonBody
			req.GetBody = func() (io.ReadCloser, error) {
				return io.NopCloser(bytes.NewReader(bodyBytes)), nil
			}
		}
		req.Header.Set("Accept", accept)
		if c.userAgent != "" {
			req.Header.Set("User-Agent", c.userAgent)
		}
		for _, h := range headers {
			for k, vs := range h {
				for _, v := range vs {
					req.Header.Set(k, v)
				}
			}
		}

		if c.auth != nil {
			if err := c.auth.Apply(req); err != nil {
				return fmt.Errorf("applying auth: %w", err)
			}
		}

		resp, err := transport(req)
		if err != nil {
			// Network errors are not retryable.
			return fmt.Errorf("executing request: %w", err)
		}

		respBody, err := io.ReadAll(resp.Body)
		resp.Body.Close()
		if err != nil {
			return fmt.Errorf("reading response body: %w", err)
		}

		// Check if we should retry.
		if c.retryConfig != nil && attempt < maxAttempts-1 && shouldRetry(resp.StatusCode, *c.retryConfig) {
			delay := retryDelay(attempt, *c.retryConfig, resp)
			timer := time.NewTimer(delay)
			select {
			case <-ctx.Done():
				timer.Stop()
				return ctx.Err()
			case <-timer.C:
			}
			continue
		}

		if resp.StatusCode < 200 || resp.StatusCode >= 300 {
			return &APIError{StatusCode: resp.StatusCode, Status: resp.Status, Body: respBody}
		}

		if result != nil && len(respBody) > 0 {
			ct := resp.Header.Get("Content-Type")
			if strings.Contains(ct, "json") || ct == "" {
				if err := json.Unmarshal(respBody, result); err != nil {
					return fmt.Errorf("decoding response body: %w", err)
				}
			} else if s, ok := result.(*string); ok {
				*s = string(respBody)
			} else {
				if err := json.Unmarshal(respBody, result); err != nil {
					return fmt.Errorf("decoding response body: %w", err)
				}
			}
		}

		return nil
	}

	return fmt.Errorf("max retries exceeded")
}
