// Code generated by openapi-client-generator. DO NOT EDIT.

package parallelworks

import (
	"encoding/json"
	"errors"
	"fmt"
	"mime"
	"net/http"
)

// Sentinel errors for common HTTP status codes. Use with errors.Is:
//
//	if errors.Is(err, ErrNotFound) { ... }
var (
	ErrBadRequest          = &APIError{StatusCode: http.StatusBadRequest}
	ErrUnauthorized        = &APIError{StatusCode: http.StatusUnauthorized}
	ErrForbidden           = &APIError{StatusCode: http.StatusForbidden}
	ErrNotFound            = &APIError{StatusCode: http.StatusNotFound}
	ErrConflict            = &APIError{StatusCode: http.StatusConflict}
	ErrTooManyRequests     = &APIError{StatusCode: http.StatusTooManyRequests}
	ErrInternalServerError = &APIError{StatusCode: http.StatusInternalServerError}
	ErrBadGateway          = &APIError{StatusCode: http.StatusBadGateway}
	ErrServiceUnavailable  = &APIError{StatusCode: http.StatusServiceUnavailable}
	ErrGatewayTimeout      = &APIError{StatusCode: http.StatusGatewayTimeout}
)

// APIError represents a non-2xx HTTP response.
type APIError struct {
	StatusCode  int
	Status      string
	ContentType string
	Body        []byte
}

func (e *APIError) Error() string {
	if p := e.Problem(); p != nil {
		if p.Detail != "" {
			return fmt.Sprintf("API error %s: %s", e.statusLabel(), p.Detail)
		}
		if p.Title != "" {
			return fmt.Sprintf("API error %s: %s", e.statusLabel(), p.Title)
		}
	}
	if len(e.Body) > 0 {
		return fmt.Sprintf("API error %s: %s", e.statusLabel(), e.Body)
	}
	return fmt.Sprintf("API error %s", e.statusLabel())
}

// statusLabel reconstructs the label from StatusCode for the sentinel errors,
// which set only StatusCode; Status already carries the code (e.g. "409
// Conflict"), so the code is never printed twice.
func (e *APIError) statusLabel() string {
	if e.Status != "" {
		return e.Status
	}
	if text := http.StatusText(e.StatusCode); text != "" {
		return fmt.Sprintf("%d %s", e.StatusCode, text)
	}
	return fmt.Sprintf("%d", e.StatusCode)
}

// ProblemDetails is an RFC 9457 problem details object.
type ProblemDetails struct {
	Type     string `json:"type,omitempty"`
	Title    string `json:"title,omitempty"`
	Status   int    `json:"status,omitempty"`
	Detail   string `json:"detail,omitempty"`
	Instance string `json:"instance,omitempty"`
	// Extensions holds every other member, such as an error code, by name.
	Extensions map[string]json.RawMessage `json:"-"`
}

// Problem returns the body as RFC 9457 problem details when the response is
// application/problem+json, and nil otherwise.
func (e *APIError) Problem() *ProblemDetails {
	if mediaType, _, _ := mime.ParseMediaType(e.ContentType); mediaType != "application/problem+json" {
		return nil
	}
	var p ProblemDetails
	var members map[string]json.RawMessage
	if json.Unmarshal(e.Body, &p) != nil || json.Unmarshal(e.Body, &members) != nil {
		return nil
	}
	for _, name := range []string{"type", "title", "status", "detail", "instance"} {
		delete(members, name)
	}
	if len(members) > 0 {
		p.Extensions = members
	}
	return &p
}

// Is supports errors.Is by matching on status code.
func (e *APIError) Is(target error) bool {
	t, ok := target.(*APIError)
	if !ok {
		return false
	}
	return e.StatusCode == t.StatusCode
}

// ErrorResponse wraps an APIError with a parsed Error body.
type ErrorResponse struct {
	*APIError
	Detail Error
}

func (e *ErrorResponse) Error() string {
	if e.Detail.Message != "" {
		return fmt.Sprintf("API error %s: %s", e.statusLabel(), e.Detail.Message)
	}
	return e.APIError.Error()
}

func (e *ErrorResponse) Unwrap() error {
	return e.APIError
}

func parseErrorResponse(err error) error {
	var apiErr *APIError
	if !errors.As(err, &apiErr) || len(apiErr.Body) == 0 {
		return err
	}
	resp := &ErrorResponse{APIError: apiErr}
	if json.Unmarshal(apiErr.Body, &resp.Detail) == nil {
		return resp
	}
	return err
}
