// Code generated by openapi-client-generator. DO NOT EDIT.
package parallelworks

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
)

// Sentinel errors for common HTTP status codes. Use with errors.Is:
//
//	if errors.Is(err, ErrNotFound) { ... }
var (
	ErrBadRequest          = &APIError{StatusCode: http.StatusBadRequest}
	ErrUnauthorized        = &APIError{StatusCode: http.StatusUnauthorized}
	ErrForbidden           = &APIError{StatusCode: http.StatusForbidden}
	ErrNotFound            = &APIError{StatusCode: http.StatusNotFound}
	ErrConflict            = &APIError{StatusCode: http.StatusConflict}
	ErrTooManyRequests     = &APIError{StatusCode: http.StatusTooManyRequests}
	ErrInternalServerError = &APIError{StatusCode: http.StatusInternalServerError}
	ErrBadGateway          = &APIError{StatusCode: http.StatusBadGateway}
	ErrServiceUnavailable  = &APIError{StatusCode: http.StatusServiceUnavailable}
	ErrGatewayTimeout      = &APIError{StatusCode: http.StatusGatewayTimeout}
)

// APIError represents a non-2xx HTTP response.
type APIError struct {
	StatusCode int
	Status     string
	Body       []byte
}

func (e *APIError) Error() string {
	if len(e.Body) > 0 {
		return fmt.Sprintf("API error %d %s: %s", e.StatusCode, e.Status, string(e.Body))
	}
	return fmt.Sprintf("API error %d", e.StatusCode)
}

// Is supports errors.Is by matching on status code.
func (e *APIError) Is(target error) bool {
	t, ok := target.(*APIError)
	if !ok {
		return false
	}
	return e.StatusCode == t.StatusCode
}

// ErrorResponse wraps an APIError with a parsed Error body.
type ErrorResponse struct {
	*APIError
	Detail Error
}

func (e *ErrorResponse) Error() string {
	return e.APIError.Error()
}

func (e *ErrorResponse) Unwrap() error {
	return e.APIError
}

func parseErrorError(err error) error {
	var apiErr *APIError
	if !errors.As(err, &apiErr) || len(apiErr.Body) == 0 {
		return err
	}
	resp := &ErrorResponse{APIError: apiErr}
	if json.Unmarshal(apiErr.Body, &resp.Detail) == nil {
		return resp
	}
	return err
}
