// Code generated by openapi-client-generator. DO NOT EDIT.

package parallelworks

import (
	"fmt"
	"net/url"
	"strings"
)

// pathReplace replaces a {param} placeholder in a URL path with the given value.
func pathReplace(path, param string, value any) string {
	return strings.Replace(path, "{"+param+"}", fmt.Sprintf("%v", value), 1)
}

// addQueryParam adds a non-zero-value query parameter.
func addQueryParam(values url.Values, key string, value any) {
	if value == nil {
		return
	}
	s := fmt.Sprintf("%v", value)
	if s != "" && s != "0" && s != "false" {
		values.Set(key, s)
	}
}
