// Code generated by openapi-client-generator. DO NOT EDIT.

package parallelworks

import (
	"fmt"
	"net/url"
	"reflect"
	"strings"
)

// pathReplace replaces a {param} placeholder in a URL path with the given value.
func pathReplace(path, param string, value any) string {
	return strings.Replace(path, "{"+param+"}", fmt.Sprintf("%v", value), 1)
}

// addQueryParam adds a non-zero-value query parameter.
// It handles pointer types by dereferencing them before formatting.
func addQueryParam(values url.Values, key string, value any) {
	if value == nil {
		return
	}
	// Dereference pointer types to get the underlying value.
	rv := reflect.ValueOf(value)
	if rv.Kind() == reflect.Pointer {
		if rv.IsNil() {
			return
		}
		value = rv.Elem().Interface()
	}
	s := fmt.Sprintf("%v", value)
	if s != "" && s != "0" && s != "false" {
		values.Set(key, s)
	}
}
