// Code generated by openapi-client-generator. DO NOT EDIT.

package parallelworks

import "net/http"

// RoundTripFunc is a function that executes an HTTP request.
type RoundTripFunc func(*http.Request) (*http.Response, error)

// Middleware wraps an HTTP round trip.
type Middleware func(req *http.Request, next RoundTripFunc) (*http.Response, error)

// WithMiddleware adds middleware to the client.
func WithMiddleware(mw ...Middleware) ClientOption {
	return func(c *Client) {
		c.middlewares = append(c.middlewares, mw...)
	}
}
