// Code generated by openapi-client-generator. DO NOT EDIT.
package parallelworks

import "net/http"

// ClientOption configures the Client.
type ClientOption func(*Client)

// WithHTTPClient sets the HTTP client used for requests.
func WithHTTPClient(c *http.Client) ClientOption {
	return func(cl *Client) {
		cl.httpClient = c
	}
}

// WithUserAgent sets the User-Agent header for all requests.
func WithUserAgent(ua string) ClientOption {
	return func(cl *Client) {
		cl.userAgent = ua
	}
}
