// Code generated by openapi-client-generator. DO NOT EDIT.
package parallelworks

// PageIterator provides iteration over paginated API results.
type PageIterator[T any] struct {
	fetch      func(cursor string) ([]T, string, error)
	nextCursor string
	done       bool
}

// Next fetches the next page of results. Returns nil, nil when no more pages.
func (it *PageIterator[T]) Next() ([]T, error) {
	if it.done {
		return nil, nil
	}
	items, next, err := it.fetch(it.nextCursor)
	if err != nil {
		return nil, err
	}
	if next == "" {
		it.done = true
	}
	it.nextCursor = next
	return items, nil
}

// All fetches all remaining pages and returns all items.
func (it *PageIterator[T]) All() ([]T, error) {
	var all []T
	for {
		items, err := it.Next()
		if err != nil {
			return all, err
		}
		if items == nil {
			break
		}
		all = append(all, items...)
	}
	return all, nil
}

// ForEach calls fn for each item across all pages. Stops on first error from fn.
func (it *PageIterator[T]) ForEach(fn func(T) error) error {
	for {
		items, err := it.Next()
		if err != nil {
			return err
		}
		if items == nil {
			return nil
		}
		for _, item := range items {
			if err := fn(item); err != nil {
				return err
			}
		}
	}
}
