// Code generated by openapi-client-generator. DO NOT EDIT.

package parallelworks

import (
	"context"
	"net/http"
	"strconv"
)

// ResponseMeta carries what a response says outside its body: the status it
// arrived with and the headers it carried.
type ResponseMeta struct {
	StatusCode int
	Status     string
	Header     http.Header
}

type responseCaptureKey struct{}

// WithResponseCapture returns a context that records what the next response says
// outside its body, and the ResponseMeta it lands in. Calls made with the
// returned context each overwrite it, so give one capture to one call.
//
//	ctx, meta := WithResponseCapture(ctx)
//	pet, err := client.GetPetByID(ctx, 123)
//	fmt.Println(meta.StatusCode, meta.Header.Get("X-Request-Id"))
//
// An error response is captured too, so the status and headers are readable
// whether or not the call succeeded.
func WithResponseCapture(ctx context.Context) (context.Context, *ResponseMeta) {
	meta := &ResponseMeta{}
	return context.WithValue(ctx, responseCaptureKey{}, meta), meta
}

// captureResponse records resp on the ResponseMeta the caller attached to ctx.
func captureResponse(ctx context.Context, resp *http.Response) {
	meta, ok := ctx.Value(responseCaptureKey{}).(*ResponseMeta)
	if !ok || resp == nil {
		return
	}
	meta.StatusCode = resp.StatusCode
	meta.Status = resp.Status
	meta.Header = resp.Header.Clone()
}

// headerInt64 parses a header declared as an integer. It returns nil when the
// header is absent or does not parse, which a value type could not distinguish
// from a legitimate zero.
func headerInt64(h http.Header, name string) *int64 {
	raw := h.Get(name)
	if raw == "" {
		return nil
	}
	v, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		return nil
	}
	return &v
}

// GetAcmeChallengeHeaders holds the headers GetAcmeChallenge declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetAcmeChallengeHeaders struct {
	ContentType string
}

// GetAcmeChallengeHeaders reads the headers GetAcmeChallenge declares out of the captured
// response.
func (m *ResponseMeta) GetAcmeChallengeHeaders() GetAcmeChallengeHeaders {
	return GetAcmeChallengeHeaders{
		ContentType: m.Header.Get("Content-Type"),
	}
}

// GetPkiValidationFileHeaders holds the headers GetPkiValidationFile declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetPkiValidationFileHeaders struct {
	ContentType string
}

// GetPkiValidationFileHeaders reads the headers GetPkiValidationFile declares out of the captured
// response.
func (m *ResponseMeta) GetPkiValidationFileHeaders() GetPkiValidationFileHeaders {
	return GetPkiValidationFileHeaders{
		ContentType: m.Header.Get("Content-Type"),
	}
}

// RegisterNodeHeaders holds the headers RegisterNode declares. A header the spec
// types as something other than a string is nil when the response omits it.
type RegisterNodeHeaders struct {
	CacheControl string
}

// RegisterNodeHeaders reads the headers RegisterNode declares out of the captured
// response.
func (m *ResponseMeta) RegisterNodeHeaders() RegisterNodeHeaders {
	return RegisterNodeHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
	}
}

// DownloadAiChatAttachmentDirectHeaders holds the headers DownloadAiChatAttachmentDirect declares. A header the spec
// types as something other than a string is nil when the response omits it.
type DownloadAiChatAttachmentDirectHeaders struct {
	ContentDisposition    string
	ContentLength         *int64
	ContentSecurityPolicy string
	ContentType           string
	XContentTypeOptions   string
}

// DownloadAiChatAttachmentDirectHeaders reads the headers DownloadAiChatAttachmentDirect declares out of the captured
// response.
func (m *ResponseMeta) DownloadAiChatAttachmentDirectHeaders() DownloadAiChatAttachmentDirectHeaders {
	return DownloadAiChatAttachmentDirectHeaders{
		ContentDisposition:    m.Header.Get("Content-Disposition"),
		ContentLength:         headerInt64(m.Header, "Content-Length"),
		ContentSecurityPolicy: m.Header.Get("Content-Security-Policy"),
		ContentType:           m.Header.Get("Content-Type"),
		XContentTypeOptions:   m.Header.Get("X-Content-Type-Options"),
	}
}

// DownloadAiChatAttachmentHeaders holds the headers DownloadAiChatAttachment declares. A header the spec
// types as something other than a string is nil when the response omits it.
type DownloadAiChatAttachmentHeaders struct {
	ContentDisposition    string
	ContentLength         *int64
	ContentSecurityPolicy string
	ContentType           string
	XContentTypeOptions   string
}

// DownloadAiChatAttachmentHeaders reads the headers DownloadAiChatAttachment declares out of the captured
// response.
func (m *ResponseMeta) DownloadAiChatAttachmentHeaders() DownloadAiChatAttachmentHeaders {
	return DownloadAiChatAttachmentHeaders{
		ContentDisposition:    m.Header.Get("Content-Disposition"),
		ContentLength:         headerInt64(m.Header, "Content-Length"),
		ContentSecurityPolicy: m.Header.Get("Content-Security-Policy"),
		ContentType:           m.Header.Get("Content-Type"),
		XContentTypeOptions:   m.Header.Get("X-Content-Type-Options"),
	}
}

// CreateApikeyHeaders holds the headers CreateApikey declares. A header the spec
// types as something other than a string is nil when the response omits it.
type CreateApikeyHeaders struct {
	CacheControl string
}

// CreateApikeyHeaders reads the headers CreateApikey declares out of the captured
// response.
func (m *ResponseMeta) CreateApikeyHeaders() CreateApikeyHeaders {
	return CreateApikeyHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
	}
}

// GetAuthSsoOidcCallbackHeaders holds the headers GetAuthSsoOidcCallback declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetAuthSsoOidcCallbackHeaders struct {
	Location  string
	SetCookie string
}

// GetAuthSsoOidcCallbackHeaders reads the headers GetAuthSsoOidcCallback declares out of the captured
// response.
func (m *ResponseMeta) GetAuthSsoOidcCallbackHeaders() GetAuthSsoOidcCallbackHeaders {
	return GetAuthSsoOidcCallbackHeaders{
		Location:  m.Header.Get("Location"),
		SetCookie: m.Header.Get("Set-Cookie"),
	}
}

// GetAuthSsoOidcRedirectHeaders holds the headers GetAuthSsoOidcRedirect declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetAuthSsoOidcRedirectHeaders struct {
	Location  string
	SetCookie string
}

// GetAuthSsoOidcRedirectHeaders reads the headers GetAuthSsoOidcRedirect declares out of the captured
// response.
func (m *ResponseMeta) GetAuthSsoOidcRedirectHeaders() GetAuthSsoOidcRedirectHeaders {
	return GetAuthSsoOidcRedirectHeaders{
		Location:  m.Header.Get("Location"),
		SetCookie: m.Header.Get("Set-Cookie"),
	}
}

// GetAuthTokenHeaders holds the headers GetAuthToken declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetAuthTokenHeaders struct {
	CacheControl string
}

// GetAuthTokenHeaders reads the headers GetAuthToken declares out of the captured
// response.
func (m *ResponseMeta) GetAuthTokenHeaders() GetAuthTokenHeaders {
	return GetAuthTokenHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
	}
}

// GetAuthTokenOidcHeaders holds the headers GetAuthTokenOidc declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetAuthTokenOidcHeaders struct {
	CacheControl string
}

// GetAuthTokenOidcHeaders reads the headers GetAuthTokenOidc declares out of the captured
// response.
func (m *ResponseMeta) GetAuthTokenOidcHeaders() GetAuthTokenOidcHeaders {
	return GetAuthTokenOidcHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
	}
}

// GetWhoamiHeaders holds the headers GetWhoami declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetWhoamiHeaders struct {
	ContentType string
}

// GetWhoamiHeaders reads the headers GetWhoami declares out of the captured
// response.
func (m *ResponseMeta) GetWhoamiHeaders() GetWhoamiHeaders {
	return GetWhoamiHeaders{
		ContentType: m.Header.Get("Content-Type"),
	}
}

// GetUserAvatarHeaders holds the headers GetUserAvatar declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetUserAvatarHeaders struct {
	CacheControl        string
	ContentType         string
	ETag                string
	Location            string
	XContentTypeOptions string
}

// GetUserAvatarHeaders reads the headers GetUserAvatar declares out of the captured
// response.
func (m *ResponseMeta) GetUserAvatarHeaders() GetUserAvatarHeaders {
	return GetUserAvatarHeaders{
		CacheControl:        m.Header.Get("Cache-Control"),
		ContentType:         m.Header.Get("Content-Type"),
		ETag:                m.Header.Get("ETag"),
		Location:            m.Header.Get("Location"),
		XContentTypeOptions: m.Header.Get("X-Content-Type-Options"),
	}
}

// ServeBlobHeaders holds the headers ServeBlob declares. A header the spec
// types as something other than a string is nil when the response omits it.
type ServeBlobHeaders struct {
	CacheControl        string
	ContentType         string
	ETag                string
	Location            string
	XContentTypeOptions string
}

// ServeBlobHeaders reads the headers ServeBlob declares out of the captured
// response.
func (m *ResponseMeta) ServeBlobHeaders() ServeBlobHeaders {
	return ServeBlobHeaders{
		CacheControl:        m.Header.Get("Cache-Control"),
		ContentType:         m.Header.Get("Content-Type"),
		ETag:                m.Header.Get("ETag"),
		Location:            m.Header.Get("Location"),
		XContentTypeOptions: m.Header.Get("X-Content-Type-Options"),
	}
}

// GetChangelogAuthorAvatarHeaders holds the headers GetChangelogAuthorAvatar declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetChangelogAuthorAvatarHeaders struct {
	CacheControl string
	ContentType  string
}

// GetChangelogAuthorAvatarHeaders reads the headers GetChangelogAuthorAvatar declares out of the captured
// response.
func (m *ResponseMeta) GetChangelogAuthorAvatarHeaders() GetChangelogAuthorAvatarHeaders {
	return GetChangelogAuthorAvatarHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
		ContentType:  m.Header.Get("Content-Type"),
	}
}

// UpdateInstanceStatusHeaders holds the headers UpdateInstanceStatus declares. A header the spec
// types as something other than a string is nil when the response omits it.
type UpdateInstanceStatusHeaders struct {
	Csp                   string
	CspID                 string
	Hostname              string
	ID                    string
	ProvisionOutputStatus string
}

// UpdateInstanceStatusHeaders reads the headers UpdateInstanceStatus declares out of the captured
// response.
func (m *ResponseMeta) UpdateInstanceStatusHeaders() UpdateInstanceStatusHeaders {
	return UpdateInstanceStatusHeaders{
		Csp:                   m.Header.Get("Csp"),
		CspID:                 m.Header.Get("CspId"),
		Hostname:              m.Header.Get("Hostname"),
		ID:                    m.Header.Get("Id"),
		ProvisionOutputStatus: m.Header.Get("ProvisionOutputStatus"),
	}
}

// GithubOauthAuthorizeHeaders holds the headers GithubOauthAuthorize declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GithubOauthAuthorizeHeaders struct {
	Location  string
	SetCookie string
}

// GithubOauthAuthorizeHeaders reads the headers GithubOauthAuthorize declares out of the captured
// response.
func (m *ResponseMeta) GithubOauthAuthorizeHeaders() GithubOauthAuthorizeHeaders {
	return GithubOauthAuthorizeHeaders{
		Location:  m.Header.Get("Location"),
		SetCookie: m.Header.Get("Set-Cookie"),
	}
}

// GithubOauthCallbackHeaders holds the headers GithubOauthCallback declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GithubOauthCallbackHeaders struct {
	Location  string
	SetCookie string
}

// GithubOauthCallbackHeaders reads the headers GithubOauthCallback declares out of the captured
// response.
func (m *ResponseMeta) GithubOauthCallbackHeaders() GithubOauthCallbackHeaders {
	return GithubOauthCallbackHeaders{
		Location:  m.Header.Get("Location"),
		SetCookie: m.Header.Get("Set-Cookie"),
	}
}

// GitlabOauthCallbackHeaders holds the headers GitlabOauthCallback declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GitlabOauthCallbackHeaders struct {
	Location  string
	SetCookie string
}

// GitlabOauthCallbackHeaders reads the headers GitlabOauthCallback declares out of the captured
// response.
func (m *ResponseMeta) GitlabOauthCallbackHeaders() GitlabOauthCallbackHeaders {
	return GitlabOauthCallbackHeaders{
		Location:  m.Header.Get("Location"),
		SetCookie: m.Header.Get("Set-Cookie"),
	}
}

// GetMarketplaceIconHeaders holds the headers GetMarketplaceIcon declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetMarketplaceIconHeaders struct {
	CacheControl        string
	ContentType         string
	ETag                string
	Location            string
	XContentTypeOptions string
}

// GetMarketplaceIconHeaders reads the headers GetMarketplaceIcon declares out of the captured
// response.
func (m *ResponseMeta) GetMarketplaceIconHeaders() GetMarketplaceIconHeaders {
	return GetMarketplaceIconHeaders{
		CacheControl:        m.Header.Get("Cache-Control"),
		ContentType:         m.Header.Get("Content-Type"),
		ETag:                m.Header.Get("ETag"),
		Location:            m.Header.Get("Location"),
		XContentTypeOptions: m.Header.Get("X-Content-Type-Options"),
	}
}

// GetOidcAuthorizeHeaders holds the headers GetOidcAuthorize declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetOidcAuthorizeHeaders struct {
	Location  string
	SetCookie string
}

// GetOidcAuthorizeHeaders reads the headers GetOidcAuthorize declares out of the captured
// response.
func (m *ResponseMeta) GetOidcAuthorizeHeaders() GetOidcAuthorizeHeaders {
	return GetOidcAuthorizeHeaders{
		Location:  m.Header.Get("Location"),
		SetCookie: m.Header.Get("Set-Cookie"),
	}
}

// GetOidcAuthorizeResumeHeaders holds the headers GetOidcAuthorizeResume declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetOidcAuthorizeResumeHeaders struct {
	Location  string
	SetCookie string
}

// GetOidcAuthorizeResumeHeaders reads the headers GetOidcAuthorizeResume declares out of the captured
// response.
func (m *ResponseMeta) GetOidcAuthorizeResumeHeaders() GetOidcAuthorizeResumeHeaders {
	return GetOidcAuthorizeResumeHeaders{
		Location:  m.Header.Get("Location"),
		SetCookie: m.Header.Get("Set-Cookie"),
	}
}

// PostOidcConsentHeaders holds the headers PostOidcConsent declares. A header the spec
// types as something other than a string is nil when the response omits it.
type PostOidcConsentHeaders struct {
	SetCookie string
}

// PostOidcConsentHeaders reads the headers PostOidcConsent declares out of the captured
// response.
func (m *ResponseMeta) PostOidcConsentHeaders() PostOidcConsentHeaders {
	return PostOidcConsentHeaders{
		SetCookie: m.Header.Get("Set-Cookie"),
	}
}

// PostOidcTokenHeaders holds the headers PostOidcToken declares. A header the spec
// types as something other than a string is nil when the response omits it.
type PostOidcTokenHeaders struct {
	CacheControl    string
	WwwAuthenticate string
}

// PostOidcTokenHeaders reads the headers PostOidcToken declares out of the captured
// response.
func (m *ResponseMeta) PostOidcTokenHeaders() PostOidcTokenHeaders {
	return PostOidcTokenHeaders{
		CacheControl:    m.Header.Get("Cache-Control"),
		WwwAuthenticate: m.Header.Get("WWW-Authenticate"),
	}
}

// GetOidcTokenDirectHeaders holds the headers GetOidcTokenDirect declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetOidcTokenDirectHeaders struct {
	CacheControl string
}

// GetOidcTokenDirectHeaders reads the headers GetOidcTokenDirect declares out of the captured
// response.
func (m *ResponseMeta) GetOidcTokenDirectHeaders() GetOidcTokenDirectHeaders {
	return GetOidcTokenDirectHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
	}
}

// GetOidcUserinfoHeaders holds the headers GetOidcUserinfo declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetOidcUserinfoHeaders struct {
	CacheControl string
}

// GetOidcUserinfoHeaders reads the headers GetOidcUserinfo declares out of the captured
// response.
func (m *ResponseMeta) GetOidcUserinfoHeaders() GetOidcUserinfoHeaders {
	return GetOidcUserinfoHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
	}
}

// PostOidcUserinfoHeaders holds the headers PostOidcUserinfo declares. A header the spec
// types as something other than a string is nil when the response omits it.
type PostOidcUserinfoHeaders struct {
	CacheControl string
}

// PostOidcUserinfoHeaders reads the headers PostOidcUserinfo declares out of the captured
// response.
func (m *ResponseMeta) PostOidcUserinfoHeaders() PostOidcUserinfoHeaders {
	return PostOidcUserinfoHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
	}
}

// GetManagedClusterIconHeaders holds the headers GetManagedClusterIcon declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetManagedClusterIconHeaders struct {
	CacheControl        string
	ContentType         string
	ETag                string
	Location            string
	XContentTypeOptions string
}

// GetManagedClusterIconHeaders reads the headers GetManagedClusterIcon declares out of the captured
// response.
func (m *ResponseMeta) GetManagedClusterIconHeaders() GetManagedClusterIconHeaders {
	return GetManagedClusterIconHeaders{
		CacheControl:        m.Header.Get("Cache-Control"),
		ContentType:         m.Header.Get("Content-Type"),
		ETag:                m.Header.Get("ETag"),
		Location:            m.Header.Get("Location"),
		XContentTypeOptions: m.Header.Get("X-Content-Type-Options"),
	}
}

// GenerateNodeTokenHeaders holds the headers GenerateNodeToken declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GenerateNodeTokenHeaders struct {
	CacheControl string
}

// GenerateNodeTokenHeaders reads the headers GenerateNodeToken declares out of the captured
// response.
func (m *ResponseMeta) GenerateNodeTokenHeaders() GenerateNodeTokenHeaders {
	return GenerateNodeTokenHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
	}
}

// CreateOrgOidcAppSecretHeaders holds the headers CreateOrgOidcAppSecret declares. A header the spec
// types as something other than a string is nil when the response omits it.
type CreateOrgOidcAppSecretHeaders struct {
	CacheControl string
}

// CreateOrgOidcAppSecretHeaders reads the headers CreateOrgOidcAppSecret declares out of the captured
// response.
func (m *ResponseMeta) CreateOrgOidcAppSecretHeaders() CreateOrgOidcAppSecretHeaders {
	return CreateOrgOidcAppSecretHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
	}
}

// RotateOrgOidcAppSecretHeaders holds the headers RotateOrgOidcAppSecret declares. A header the spec
// types as something other than a string is nil when the response omits it.
type RotateOrgOidcAppSecretHeaders struct {
	CacheControl string
}

// RotateOrgOidcAppSecretHeaders reads the headers RotateOrgOidcAppSecret declares out of the captured
// response.
func (m *ResponseMeta) RotateOrgOidcAppSecretHeaders() RotateOrgOidcAppSecretHeaders {
	return RotateOrgOidcAppSecretHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
	}
}

// RevealOrgOidcAppSecretHeaders holds the headers RevealOrgOidcAppSecret declares. A header the spec
// types as something other than a string is nil when the response omits it.
type RevealOrgOidcAppSecretHeaders struct {
	CacheControl string
}

// RevealOrgOidcAppSecretHeaders reads the headers RevealOrgOidcAppSecret declares out of the captured
// response.
func (m *ResponseMeta) RevealOrgOidcAppSecretHeaders() RevealOrgOidcAppSecretHeaders {
	return RevealOrgOidcAppSecretHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
	}
}

// CreateScimTokenHeaders holds the headers CreateScimToken declares. A header the spec
// types as something other than a string is nil when the response omits it.
type CreateScimTokenHeaders struct {
	CacheControl string
}

// CreateScimTokenHeaders reads the headers CreateScimToken declares out of the captured
// response.
func (m *ResponseMeta) CreateScimTokenHeaders() CreateScimTokenHeaders {
	return CreateScimTokenHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
	}
}

// GetOrgUserAvatarHeaders holds the headers GetOrgUserAvatar declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetOrgUserAvatarHeaders struct {
	CacheControl        string
	ContentType         string
	ETag                string
	Location            string
	XContentTypeOptions string
}

// GetOrgUserAvatarHeaders reads the headers GetOrgUserAvatar declares out of the captured
// response.
func (m *ResponseMeta) GetOrgUserAvatarHeaders() GetOrgUserAvatarHeaders {
	return GetOrgUserAvatarHeaders{
		CacheControl:        m.Header.Get("Cache-Control"),
		ContentType:         m.Header.Get("Content-Type"),
		ETag:                m.Header.Get("ETag"),
		Location:            m.Header.Get("Location"),
		XContentTypeOptions: m.Header.Get("X-Content-Type-Options"),
	}
}

// GetTokenAwsBucketHeaders holds the headers GetTokenAwsBucket declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetTokenAwsBucketHeaders struct {
	CacheControl string
}

// GetTokenAwsBucketHeaders reads the headers GetTokenAwsBucket declares out of the captured
// response.
func (m *ResponseMeta) GetTokenAwsBucketHeaders() GetTokenAwsBucketHeaders {
	return GetTokenAwsBucketHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
	}
}

// GetTokenAzureBucketHeaders holds the headers GetTokenAzureBucket declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetTokenAzureBucketHeaders struct {
	CacheControl string
}

// GetTokenAzureBucketHeaders reads the headers GetTokenAzureBucket declares out of the captured
// response.
func (m *ResponseMeta) GetTokenAzureBucketHeaders() GetTokenAzureBucketHeaders {
	return GetTokenAzureBucketHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
	}
}

// GitlabOauthAuthorizeHeaders holds the headers GitlabOauthAuthorize declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GitlabOauthAuthorizeHeaders struct {
	Location  string
	SetCookie string
}

// GitlabOauthAuthorizeHeaders reads the headers GitlabOauthAuthorize declares out of the captured
// response.
func (m *ResponseMeta) GitlabOauthAuthorizeHeaders() GitlabOauthAuthorizeHeaders {
	return GitlabOauthAuthorizeHeaders{
		Location:  m.Header.Get("Location"),
		SetCookie: m.Header.Get("Set-Cookie"),
	}
}

// GetTokenGoogleBucketHeaders holds the headers GetTokenGoogleBucket declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetTokenGoogleBucketHeaders struct {
	CacheControl string
}

// GetTokenGoogleBucketHeaders reads the headers GetTokenGoogleBucket declares out of the captured
// response.
func (m *ResponseMeta) GetTokenGoogleBucketHeaders() GetTokenGoogleBucketHeaders {
	return GetTokenGoogleBucketHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
	}
}

// GetAzureMachineLearningWorkspaceHeaders holds the headers GetAzureMachineLearningWorkspace declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetAzureMachineLearningWorkspaceHeaders struct {
	CacheControl string
}

// GetAzureMachineLearningWorkspaceHeaders reads the headers GetAzureMachineLearningWorkspace declares out of the captured
// response.
func (m *ResponseMeta) GetAzureMachineLearningWorkspaceHeaders() GetAzureMachineLearningWorkspaceHeaders {
	return GetAzureMachineLearningWorkspaceHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
	}
}

// GetPresignedURLMachineLearningWorkspaceHeaders holds the headers GetPresignedURLMachineLearningWorkspace declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetPresignedURLMachineLearningWorkspaceHeaders struct {
	CacheControl string
}

// GetPresignedURLMachineLearningWorkspaceHeaders reads the headers GetPresignedURLMachineLearningWorkspace declares out of the captured
// response.
func (m *ResponseMeta) GetPresignedURLMachineLearningWorkspaceHeaders() GetPresignedURLMachineLearningWorkspaceHeaders {
	return GetPresignedURLMachineLearningWorkspaceHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
	}
}

// GetUserSessionCredentialsHeaders holds the headers GetUserSessionCredentials declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetUserSessionCredentialsHeaders struct {
	CacheControl string
}

// GetUserSessionCredentialsHeaders reads the headers GetUserSessionCredentials declares out of the captured
// response.
func (m *ResponseMeta) GetUserSessionCredentialsHeaders() GetUserSessionCredentialsHeaders {
	return GetUserSessionCredentialsHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
	}
}

// CreateSSHPrivateKeyHeaders holds the headers CreateSSHPrivateKey declares. A header the spec
// types as something other than a string is nil when the response omits it.
type CreateSSHPrivateKeyHeaders struct {
	CreatedAt     string
	Description   string
	ID            string
	KeyFile       string
	Name          string
	PublicKey     string
	SSHPrivateKey string
	Type          string
	User          string
}

// CreateSSHPrivateKeyHeaders reads the headers CreateSSHPrivateKey declares out of the captured
// response.
func (m *ResponseMeta) CreateSSHPrivateKeyHeaders() CreateSSHPrivateKeyHeaders {
	return CreateSSHPrivateKeyHeaders{
		CreatedAt:     m.Header.Get("CreatedAt"),
		Description:   m.Header.Get("Description"),
		ID:            m.Header.Get("Id"),
		KeyFile:       m.Header.Get("KeyFile"),
		Name:          m.Header.Get("Name"),
		PublicKey:     m.Header.Get("PublicKey"),
		SSHPrivateKey: m.Header.Get("SSHPrivateKey"),
		Type:          m.Header.Get("Type"),
		User:          m.Header.Get("User"),
	}
}

// CreateWorkerHeaders holds the headers CreateWorker declares. A header the spec
// types as something other than a string is nil when the response omits it.
type CreateWorkerHeaders struct {
	CacheControl string
}

// CreateWorkerHeaders reads the headers CreateWorker declares out of the captured
// response.
func (m *ResponseMeta) CreateWorkerHeaders() CreateWorkerHeaders {
	return CreateWorkerHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
	}
}

// GetDeploymentIdentityHeaders holds the headers GetDeploymentIdentity declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetDeploymentIdentityHeaders struct {
	CacheControl string
}

// GetDeploymentIdentityHeaders reads the headers GetDeploymentIdentity declares out of the captured
// response.
func (m *ResponseMeta) GetDeploymentIdentityHeaders() GetDeploymentIdentityHeaders {
	return GetDeploymentIdentityHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
	}
}

// PostPlatformSetupHeaders holds the headers PostPlatformSetup declares. A header the spec
// types as something other than a string is nil when the response omits it.
type PostPlatformSetupHeaders struct {
	SetCookie string
}

// PostPlatformSetupHeaders reads the headers PostPlatformSetup declares out of the captured
// response.
func (m *ResponseMeta) PostPlatformSetupHeaders() PostPlatformSetupHeaders {
	return PostPlatformSetupHeaders{
		SetCookie: m.Header.Get("Set-Cookie"),
	}
}

// GetAiIntegrationIconHeaders holds the headers GetAiIntegrationIcon declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetAiIntegrationIconHeaders struct {
	CacheControl        string
	ContentType         string
	ETag                string
	Location            string
	XContentTypeOptions string
}

// GetAiIntegrationIconHeaders reads the headers GetAiIntegrationIcon declares out of the captured
// response.
func (m *ResponseMeta) GetAiIntegrationIconHeaders() GetAiIntegrationIconHeaders {
	return GetAiIntegrationIconHeaders{
		CacheControl:        m.Header.Get("Cache-Control"),
		ContentType:         m.Header.Get("Content-Type"),
		ETag:                m.Header.Get("ETag"),
		Location:            m.Header.Get("Location"),
		XContentTypeOptions: m.Header.Get("X-Content-Type-Options"),
	}
}

// PostProvisionStatusHeaders holds the headers PostProvisionStatus declares. A header the spec
// types as something other than a string is nil when the response omits it.
type PostProvisionStatusHeaders struct {
	Message string
}

// PostProvisionStatusHeaders reads the headers PostProvisionStatus declares out of the captured
// response.
func (m *ResponseMeta) PostProvisionStatusHeaders() PostProvisionStatusHeaders {
	return PostProvisionStatusHeaders{
		Message: m.Header.Get("Message"),
	}
}

// PatchProvisionStatusHeaders holds the headers PatchProvisionStatus declares. A header the spec
// types as something other than a string is nil when the response omits it.
type PatchProvisionStatusHeaders struct {
	Message string
}

// PatchProvisionStatusHeaders reads the headers PatchProvisionStatus declares out of the captured
// response.
func (m *ResponseMeta) PatchProvisionStatusHeaders() PatchProvisionStatusHeaders {
	return PatchProvisionStatusHeaders{
		Message: m.Header.Get("Message"),
	}
}

// GetPlatformSettingsHeaders holds the headers GetPlatformSettings declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetPlatformSettingsHeaders struct {
	SetCookie string
}

// GetPlatformSettingsHeaders reads the headers GetPlatformSettings declares out of the captured
// response.
func (m *ResponseMeta) GetPlatformSettingsHeaders() GetPlatformSettingsHeaders {
	return GetPlatformSettingsHeaders{
		SetCookie: m.Header.Get("Set-Cookie"),
	}
}

// GetCacRedirectHeaders holds the headers GetCacRedirect declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetCacRedirectHeaders struct {
	Location  string
	SetCookie string
}

// GetCacRedirectHeaders reads the headers GetCacRedirect declares out of the captured
// response.
func (m *ResponseMeta) GetCacRedirectHeaders() GetCacRedirectHeaders {
	return GetCacRedirectHeaders{
		Location:  m.Header.Get("Location"),
		SetCookie: m.Header.Get("Set-Cookie"),
	}
}

// PostLdapSignupCallbackHeaders holds the headers PostLdapSignupCallback declares. A header the spec
// types as something other than a string is nil when the response omits it.
type PostLdapSignupCallbackHeaders struct {
	Location  string
	SetCookie string
}

// PostLdapSignupCallbackHeaders reads the headers PostLdapSignupCallback declares out of the captured
// response.
func (m *ResponseMeta) PostLdapSignupCallbackHeaders() PostLdapSignupCallbackHeaders {
	return PostLdapSignupCallbackHeaders{
		Location:  m.Header.Get("Location"),
		SetCookie: m.Header.Get("Set-Cookie"),
	}
}

// PostLdapLoginHeaders holds the headers PostLdapLogin declares. A header the spec
// types as something other than a string is nil when the response omits it.
type PostLdapLoginHeaders struct {
	Location  string
	SetCookie string
}

// PostLdapLoginHeaders reads the headers PostLdapLogin declares out of the captured
// response.
func (m *ResponseMeta) PostLdapLoginHeaders() PostLdapLoginHeaders {
	return PostLdapLoginHeaders{
		Location:  m.Header.Get("Location"),
		SetCookie: m.Header.Get("Set-Cookie"),
	}
}

// PostLogoutHeaders holds the headers PostLogout declares. A header the spec
// types as something other than a string is nil when the response omits it.
type PostLogoutHeaders struct {
	SetCookie string
}

// PostLogoutHeaders reads the headers PostLogout declares out of the captured
// response.
func (m *ResponseMeta) PostLogoutHeaders() PostLogoutHeaders {
	return PostLogoutHeaders{
		SetCookie: m.Header.Get("Set-Cookie"),
	}
}

// PostMfaLoginHeaders holds the headers PostMfaLogin declares. A header the spec
// types as something other than a string is nil when the response omits it.
type PostMfaLoginHeaders struct {
	Location  string
	SetCookie string
}

// PostMfaLoginHeaders reads the headers PostMfaLogin declares out of the captured
// response.
func (m *ResponseMeta) PostMfaLoginHeaders() PostMfaLoginHeaders {
	return PostMfaLoginHeaders{
		Location:  m.Header.Get("Location"),
		SetCookie: m.Header.Get("Set-Cookie"),
	}
}

// PostAddMfaOtpHeaders holds the headers PostAddMfaOtp declares. A header the spec
// types as something other than a string is nil when the response omits it.
type PostAddMfaOtpHeaders struct {
	CacheControl string
}

// PostAddMfaOtpHeaders reads the headers PostAddMfaOtp declares out of the captured
// response.
func (m *ResponseMeta) PostAddMfaOtpHeaders() PostAddMfaOtpHeaders {
	return PostAddMfaOtpHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
	}
}

// PostVerifyOtpHeaders holds the headers PostVerifyOtp declares. A header the spec
// types as something other than a string is nil when the response omits it.
type PostVerifyOtpHeaders struct {
	Location  string
	SetCookie string
}

// PostVerifyOtpHeaders reads the headers PostVerifyOtp declares out of the captured
// response.
func (m *ResponseMeta) PostVerifyOtpHeaders() PostVerifyOtpHeaders {
	return PostVerifyOtpHeaders{
		Location:  m.Header.Get("Location"),
		SetCookie: m.Header.Get("Set-Cookie"),
	}
}

// PostVerifyWebauthnHeaders holds the headers PostVerifyWebauthn declares. A header the spec
// types as something other than a string is nil when the response omits it.
type PostVerifyWebauthnHeaders struct {
	SetCookie string
}

// PostVerifyWebauthnHeaders reads the headers PostVerifyWebauthn declares out of the captured
// response.
func (m *ResponseMeta) PostVerifyWebauthnHeaders() PostVerifyWebauthnHeaders {
	return PostVerifyWebauthnHeaders{
		SetCookie: m.Header.Get("Set-Cookie"),
	}
}

// PatchPasswordHeaders holds the headers PatchPassword declares. A header the spec
// types as something other than a string is nil when the response omits it.
type PatchPasswordHeaders struct {
	Location  string
	SetCookie string
}

// PatchPasswordHeaders reads the headers PatchPassword declares out of the captured
// response.
func (m *ResponseMeta) PatchPasswordHeaders() PatchPasswordHeaders {
	return PatchPasswordHeaders{
		Location:  m.Header.Get("Location"),
		SetCookie: m.Header.Get("Set-Cookie"),
	}
}

// PostPasswordLoginHeaders holds the headers PostPasswordLogin declares. A header the spec
// types as something other than a string is nil when the response omits it.
type PostPasswordLoginHeaders struct {
	Location  string
	SetCookie string
}

// PostPasswordLoginHeaders reads the headers PostPasswordLogin declares out of the captured
// response.
func (m *ResponseMeta) PostPasswordLoginHeaders() PostPasswordLoginHeaders {
	return PostPasswordLoginHeaders{
		Location:  m.Header.Get("Location"),
		SetCookie: m.Header.Get("Set-Cookie"),
	}
}

// PostPasswordResetVerifyHeaders holds the headers PostPasswordResetVerify declares. A header the spec
// types as something other than a string is nil when the response omits it.
type PostPasswordResetVerifyHeaders struct {
	Location  string
	SetCookie string
}

// PostPasswordResetVerifyHeaders reads the headers PostPasswordResetVerify declares out of the captured
// response.
func (m *ResponseMeta) PostPasswordResetVerifyHeaders() PostPasswordResetVerifyHeaders {
	return PostPasswordResetVerifyHeaders{
		Location:  m.Header.Get("Location"),
		SetCookie: m.Header.Get("Set-Cookie"),
	}
}

// GetUserSSHPublicKeysHeaders holds the headers GetUserSSHPublicKeys declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetUserSSHPublicKeysHeaders struct {
	ContentType string
}

// GetUserSSHPublicKeysHeaders reads the headers GetUserSSHPublicKeys declares out of the captured
// response.
func (m *ResponseMeta) GetUserSSHPublicKeysHeaders() GetUserSSHPublicKeysHeaders {
	return GetUserSSHPublicKeysHeaders{
		ContentType: m.Header.Get("Content-Type"),
	}
}

// GetUserSSHPublicKeysLegacyHeaders holds the headers GetUserSSHPublicKeysLegacy declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetUserSSHPublicKeysLegacyHeaders struct {
	ContentType string
}

// GetUserSSHPublicKeysLegacyHeaders reads the headers GetUserSSHPublicKeysLegacy declares out of the captured
// response.
func (m *ResponseMeta) GetUserSSHPublicKeysLegacyHeaders() GetUserSSHPublicKeysLegacyHeaders {
	return GetUserSSHPublicKeysLegacyHeaders{
		ContentType: m.Header.Get("Content-Type"),
	}
}

// GetWorkflowIconHeaders holds the headers GetWorkflowIcon declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetWorkflowIconHeaders struct {
	CacheControl        string
	ContentType         string
	ETag                string
	Location            string
	XContentTypeOptions string
}

// GetWorkflowIconHeaders reads the headers GetWorkflowIcon declares out of the captured
// response.
func (m *ResponseMeta) GetWorkflowIconHeaders() GetWorkflowIconHeaders {
	return GetWorkflowIconHeaders{
		CacheControl:        m.Header.Get("Cache-Control"),
		ContentType:         m.Header.Get("Content-Type"),
		ETag:                m.Header.Get("ETag"),
		Location:            m.Header.Get("Location"),
		XContentTypeOptions: m.Header.Get("X-Content-Type-Options"),
	}
}

// GetWorkflowYamlHeaders holds the headers GetWorkflowYaml declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetWorkflowYamlHeaders struct {
	ContentType string
}

// GetWorkflowYamlHeaders reads the headers GetWorkflowYaml declares out of the captured
// response.
func (m *ResponseMeta) GetWorkflowYamlHeaders() GetWorkflowYamlHeaders {
	return GetWorkflowYamlHeaders{
		ContentType: m.Header.Get("Content-Type"),
	}
}

// GetWorkflowSchemaHeaders holds the headers GetWorkflowSchema declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GetWorkflowSchemaHeaders struct {
	CacheControl string
}

// GetWorkflowSchemaHeaders reads the headers GetWorkflowSchema declares out of the captured
// response.
func (m *ResponseMeta) GetWorkflowSchemaHeaders() GetWorkflowSchemaHeaders {
	return GetWorkflowSchemaHeaders{
		CacheControl: m.Header.Get("Cache-Control"),
	}
}
