// Code generated by openapi-client-generator. DO NOT EDIT.
package parallelworks

import (
	"math"
	"math/rand"
	"net/http"
	"strconv"
	"time"
)

// RetryConfig configures retry behavior.
type RetryConfig struct {
	// MaxRetries is the maximum number of retry attempts.
	MaxRetries int
	// BaseDelay is the initial delay before the first retry.
	BaseDelay time.Duration
	// MaxDelay is the maximum delay between retries.
	MaxDelay time.Duration
	// Multiplier is the exponential backoff multiplier.
	Multiplier float64
	// RetryableStatusCodes is the set of HTTP status codes that trigger a retry.
	RetryableStatusCodes []int
}

// DefaultRetryConfig returns sensible retry defaults.
func DefaultRetryConfig() RetryConfig {
	return RetryConfig{
		MaxRetries:           3,
		BaseDelay:            1 * time.Second,
		MaxDelay:             30 * time.Second,
		Multiplier:           2.0,
		RetryableStatusCodes: []int{429, 500, 502, 503, 504},
	}
}

// WithRetry sets a custom retry configuration.
func WithRetry(cfg RetryConfig) ClientOption {
	return func(c *Client) {
		c.retryConfig = &cfg
	}
}

// WithDefaultRetry enables retries with default configuration.
func WithDefaultRetry() ClientOption {
	return func(c *Client) {
		cfg := DefaultRetryConfig()
		c.retryConfig = &cfg
	}
}

// shouldRetry checks if a status code is retryable.
func shouldRetry(statusCode int, cfg RetryConfig) bool {
	for _, code := range cfg.RetryableStatusCodes {
		if statusCode == code {
			return true
		}
	}
	return false
}

// retryDelay calculates delay with exponential backoff, jitter, and Retry-After support.
func retryDelay(attempt int, cfg RetryConfig, resp *http.Response) time.Duration {
	// Check Retry-After header first.
	if resp != nil {
		if ra := resp.Header.Get("Retry-After"); ra != "" {
			if seconds, err := strconv.Atoi(ra); err == nil && seconds > 0 {
				return time.Duration(seconds) * time.Second
			}
		}
	}

	// Exponential backoff with jitter.
	delay := float64(cfg.BaseDelay) * math.Pow(cfg.Multiplier, float64(attempt))
	if delay > float64(cfg.MaxDelay) {
		delay = float64(cfg.MaxDelay)
	}

	// Add jitter: random value between 0 and delay.
	jitter := rand.Float64() * delay
	delay = (delay + jitter) / 2

	return time.Duration(delay)
}
