// Code generated by openapi-client-generator. DO NOT EDIT.

package parallelworks

import (
	"context"
	"crypto/tls"
	"errors"
	"math"
	"math/rand"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"
)

// RetryConfig configures retry behavior.
type RetryConfig struct {
	// MaxRetries is the maximum number of retry attempts.
	MaxRetries int
	// BaseDelay is the initial delay before the first retry.
	BaseDelay time.Duration
	// MaxDelay is the maximum delay between retries.
	MaxDelay time.Duration
	// Multiplier is the exponential backoff multiplier.
	Multiplier float64
	// RetryableStatusCodes is the set of HTTP status codes that trigger a retry.
	RetryableStatusCodes []int
}

// DefaultRetryConfig returns sensible retry defaults.
func DefaultRetryConfig() RetryConfig {
	return RetryConfig{
		MaxRetries:           3,
		BaseDelay:            1 * time.Second,
		MaxDelay:             30 * time.Second,
		Multiplier:           2.0,
		RetryableStatusCodes: []int{429, 500, 502, 503, 504},
	}
}

// WithRetry sets a custom retry configuration.
func WithRetry(cfg RetryConfig) ClientOption {
	return func(c *Client) {
		c.retryConfig = &cfg
	}
}

// WithDefaultRetry enables retries with default configuration.
func WithDefaultRetry() ClientOption {
	return func(c *Client) {
		cfg := DefaultRetryConfig()
		c.retryConfig = &cfg
	}
}

// shouldRetry checks if a status code is retryable.
func shouldRetry(statusCode int, cfg RetryConfig) bool {
	for _, code := range cfg.RetryableStatusCodes {
		if statusCode == code {
			return true
		}
	}
	return false
}

// shouldRetryStatus reports whether a response with statusCode should be retried for method.
func shouldRetryStatus(method string, statusCode int, cfg RetryConfig) bool {
	if !shouldRetry(statusCode, cfg) {
		return false
	}
	// Non-idempotent methods are only safe to retry on 429 (the request was not processed).
	return isIdempotentMethod(method) || statusCode == http.StatusTooManyRequests
}

// retryDelay calculates delay with exponential backoff, jitter, and Retry-After support.
func retryDelay(attempt int, cfg RetryConfig, resp *http.Response) time.Duration {
	if wait, ok := retryAfter(resp); ok {
		return wait
	}

	// Exponential backoff with jitter.
	delay := float64(cfg.BaseDelay) * math.Pow(cfg.Multiplier, float64(attempt))
	if delay > float64(cfg.MaxDelay) {
		delay = float64(cfg.MaxDelay)
	}

	// Add jitter: random value between 0 and delay.
	jitter := rand.Float64() * delay
	delay = (delay + jitter) / 2

	return time.Duration(delay)
}

// retryAfter returns the wait a response asks for, in either form RFC 9110
// allows, and whether it asked at all. A zero wait is an instruction like any
// other: retry now.
func retryAfter(resp *http.Response) (time.Duration, bool) {
	if resp == nil {
		return 0, false
	}
	raw := resp.Header.Get("Retry-After")
	if raw == "" {
		return 0, false
	}
	if seconds, err := strconv.Atoi(raw); err == nil {
		if seconds < 0 {
			return 0, false
		}
		return time.Duration(seconds) * time.Second, true
	}
	if at, err := http.ParseTime(raw); err == nil {
		// A date already in the past says retry now, not retry in the past.
		return max(time.Until(at), 0), true
	}
	return 0, false
}

// withinRetryBudget reports whether waiting as long as the response asks for is
// something this client agreed to. A wait past MaxDelay is not capped, since
// retrying sooner than a server asked is what the header exists to prevent: the
// call returns its error instead, leaving the caller to schedule the work with
// the header in hand.
func withinRetryBudget(resp *http.Response, cfg RetryConfig) bool {
	wait, ok := retryAfter(resp)
	return !ok || wait <= cfg.MaxDelay
}

// isIdempotentMethod reports whether method is safe to retry after a transient network error (POST is not).
func isIdempotentMethod(method string) bool {
	switch method {
	case http.MethodGet, http.MethodHead, http.MethodOptions, http.MethodPut, http.MethodDelete:
		return true
	default:
		return false
	}
}

// isRetryableNetworkError reports whether a request that got no response is
// worth sending again. The transport reports most dropped connections through
// unexported types, so the failures known to be permanent are excluded rather
// than the transient ones enumerated. An expired deadline is not excluded: a
// per-attempt http.Client.Timeout reports as one, and the caller's own context
// ends the retry loop before it waits.
func isRetryableNetworkError(err error) bool {
	if err == nil || errors.Is(err, context.Canceled) {
		return false
	}
	var certErr *tls.CertificateVerificationError
	if errors.As(err, &certErr) {
		return false
	}
	var recordErr tls.RecordHeaderError
	if errors.As(err, &recordErr) {
		return false
	}
	var urlErr *url.Error
	if errors.As(err, &urlErr) {
		msg := urlErr.Err.Error()
		return !strings.Contains(msg, "unsupported protocol scheme") && !strings.HasPrefix(msg, "stopped after ")
	}
	return true
}
