// Code generated by openapi-client-generator. DO NOT EDIT.

package parallelworks

import (
	"bufio"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"
)

// eventStreamDone is the payload OpenAI-compatible APIs send to close a stream.
// It is a marker rather than an event, so it ends iteration instead of failing
// to decode as one.
const eventStreamDone = "[DONE]"

// EventStream reads server-sent events as the server writes them. Close it when
// finished, whether or not the stream ran to its end.
//
//	stream, err := client.Whatever(ctx)
//	defer stream.Close()
//
//	for {
//		event, err := stream.Next()
//		if errors.Is(err, io.EOF) {
//			break
//		}
//		if err != nil {
//			return err
//		}
//	}
type EventStream[T any] struct {
	body   io.ReadCloser
	reader *bufio.Reader
	name   string
	id     string
}

func newEventStream[T any](resp *http.Response) *EventStream[T] {
	return &EventStream[T]{body: resp.Body, reader: bufio.NewReader(resp.Body)}
}

// Next returns the next event's payload, decoded as the spec declares it, and
// io.EOF once the server closes the stream.
func (s *EventStream[T]) Next() (T, error) {
	var zero T
	var data strings.Builder
	var name, id string

	deliver := func() (T, error) {
		payload := data.String()
		if payload == eventStreamDone {
			return zero, io.EOF
		}
		s.name, s.id = name, id
		return decodeEvent[T](payload)
	}

	for {
		line, err := s.reader.ReadString('\n')
		atEOF := errors.Is(err, io.EOF)
		if err != nil && !atEOF {
			return zero, err
		}

		switch line = strings.TrimRight(line, "\r\n"); {
		case line == "":
			// A blank line ends an event. Between events, and for the keep-alives
			// some servers send, there is nothing to end.
			if !atEOF && data.Len() > 0 {
				return deliver()
			}
		case strings.HasPrefix(line, ":"):
			// A comment, which is how keep-alives are written.
		default:
			field, value, _ := strings.Cut(line, ":")
			value = strings.TrimPrefix(value, " ")
			switch field {
			case "data":
				// Several data lines are one payload, joined by newlines.
				if data.Len() > 0 {
					data.WriteByte('\n')
				}
				data.WriteString(value)
			case "event":
				name = value
			case "id":
				id = value
			}
		}

		if atEOF {
			// A stream may end without the blank line that would have dispatched
			// what it already sent, so what arrived is delivered before EOF.
			if data.Len() == 0 {
				return zero, io.EOF
			}
			return deliver()
		}
	}
}

// EventName returns the event field of the event Next last returned, or "" for
// a stream that does not name its events.
func (s *EventStream[T]) EventName() string {
	return s.name
}

// EventID returns the id field of the event Next last returned, or "".
func (s *EventStream[T]) EventID() string {
	return s.id
}

// Close ends the stream and releases the connection.
func (s *EventStream[T]) Close() error {
	return s.body.Close()
}

// decodeEvent renders one event's data as the type the spec declares. A stream
// of text declares string, where the data is the value rather than a document.
func decodeEvent[T any](data string) (T, error) {
	var value T
	if text, ok := any(&value).(*string); ok {
		*text = data
		return value, nil
	}
	if err := json.Unmarshal([]byte(data), &value); err != nil {
		return value, fmt.Errorf("decoding event: %w", err)
	}
	return value, nil
}
